---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: RPLC_RESOURCE_CLAIM_NAME-resource-claim-policy
  namespace: RPLC_EXISTING_SECRET_NAMESPACE
spec:
  consumingNamespaces:
  - '*'
  subject:
    group: ""
    kind: Secret

---
# The ResourceClaim is a namespace scoped resource  and can be claimed only once for referencing secret: db-access-secret
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
namespace: RPLC_RESOURCECLAIM_NAMESPACE
metadata:
  name: RPLC_RESOURCE_CLAIM_NAME-resource-claim
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: RPLC_EXISTING_SECRET_REF
    namespace: RPLC_EXISTING_SECRET_NAMESPACE

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stk-secret-reader
  labels:
    servicebinding.io/controller: "true"
    resourceclaims.services.apps.tanzu.vmware.com/controller: "true"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch