---
apiVersion: v1
kind: Namespace
metadata:
  name: DEPLOYMENT_NAMESPACE
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: WORKLOAD_NAME-claim-policy
  namespace: DEPLOYMENT_NAMESPACE
spec:
  consumingNamespaces:
  - '*'
  subject:
    group: ""
    kind: Secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stk-secret-reader
  labels:
    servicebinding.io/controller: "true"
    resourceclaims.services.apps.tanzu.vmware.com/controller: "true"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch