apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  # annotations:
  #   classclaims.services.apps.tanzu.vmware.com/xrd-name: xpostgresqlinstances.database.rds.example.org
  # finalizers:
  # - classclaims.services.apps.tanzu.vmware.com/provision-finalizer
  name: RPLC_NAME
  namespace: RPLC_DEPLOYMENT_NAMESPACE
spec:
  classRef:
    name: RPLC_CLUSTER_INSTANCE_CLASS_NAME
  parameters:
    storageGB: RPLC_STORAGE_GB
    dbType: RPLC_DB_TYPE
    region: RPLC_REGION
    size: RPLC_SIZE
    publiclyAccessible: "RPLC_IS_PUBLIC"
    dbName: RPLC_DEFAULT_DB